version: '1.0'

services:
  api:
    build:
      target: api
    tty: true
    stdin_open: true
    container_name: api
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    volumes:
      - ./packages/api:/var/www/api
    ports: 
      - 8000:80
    depends_on: 
      - mysql
    networks:
      ppnetwork:
        ipv4_address: 172.20.0.10
  
  client:
    build: 
      target: client
    tty: true
    stdin_open: true
    container_name: client
    volumes:
      - ./packages/client:/app 
    ports: 
      - 3003:3003
    networks:
      ppnetwork:
        ipv4_address: 172.20.0.11  

  mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=propital
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
    ports:
      - '3306:3306'
    networks:
      ppnetwork:
        ipv4_address: 172.20.0.12 

networks:
  ppnetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16





