export const getAllComunas = [
  { id: 'Cerrillos', name: 'Cerrillos' },
  { id: 'Cerro Navia', name: 'Cerro Navia' },
  { id: 'Conchalí', name: 'Conchalí' },
  { id: 'Estación Central', name: 'Estación Central' },
  { id: 'Huechuraba', name: 'Huechuraba' },
  { id: 'Independencia', name: 'Independencia' },
  { id: 'La Cisterna', name: 'La Cisterna' },
  { id: 'La Florida', name: 'La Florida' },
  { id: 'La Granja', name: 'La Granja' },
  { id: 'La Pintana', name: 'La Pintana' },
  { id: 'La Reina', name: 'La Reina' },
  { id: 'Las Condes', name: 'Las Condes' },
  { id: 'Lo Barnechea', name: 'Lo Barnechea' },
  { id: 'Lo Espejo', name: 'Lo Espejo' },
  { id: 'Lo Prado', name: 'Lo Prado' },
  { id: 'Macul', name: 'Macul' },
  { id: 'Maipú', name: 'Maipú' },
  { id: 'Ñuñoa', name: 'Estación Central' },
  { id: 'Pedro Aguirre Cerda', name: 'Pedro Aguirre Cerda' },
  { id: 'Providencia', name: 'Providencia' },
  { id: 'Santiago', name: 'Santiago' },
];
